---
# assertion for scotch

- name: Test gcc compiler is defined
  fail:
    msg: "Please set 'gcc_version'"
  when: gcc_version is not defined

# todo
#- name: Check if make program has been defined
#  fail:
#    msg: "Please set 'scotch_make_program' to 'make' or 'ninja'"
#  when: scotch_make_program is not defined
#
#- name: Check make program is installed on the system
#  command: '{{ scotch_make_program }}'
#  register: scotch_make_program_stat
#  failed_when: "'command not found' in scotch_make_program_stat.stderr"

- name: get the rpm or apt package facts
  package_facts:
    manager: "auto"

- name: Check if environment-modules is installed on the system
  fail:
    msg:
      - "Module for {{ role_name }} is set to True but 'environment-modules' is not installed"
      - "Please install environment-modules or deactivate {{ role_name }} module creation"
  when: ansible_facts.packages['environment-modules'] is not defined and scotch_module|bool

- name: Check if build is needed
  block:
#
#    - name: Set path to requested scotch executable
#      set_fact:
#        _scotch_executable: "{{ scotch_install_dir }}/bin/scotch"
#
#    - name: Check that requested scotch exists
#      stat:
#        path: "{{ _scotch_executable }}"
#      register: stat_scotch
#
#    - name: Get gcc version
#      command: "{{ _scotch_executable }} -dumpversion"
#      register: scotch_gcc_version
#      when: stat_scotch.stat.exists

    - name: Check if build is needed
      set_fact:
        scotch_build_needed: "True"
#      when:
#        - "not stat_scotch.stat.exists or
#          (scotch_gcc_version.stdout_lines is defined  and  (scotch_gcc_version.stdout_lines[-1] != gcc_version) | bool)"
#      #todo: Add cmake options comparison for scotch source and target