---
# install tasks file for scotch

# Installing
- name: Creates scotch directories if not exists
  file:
    path: "{{ _item }}"
    state: directory
  with_items:
    - "{{ scotch_build_path }}"
    - "{{ scotch_download_path }}"
    - "{{ scotch_install_dir }}"
  loop_control:
    loop_var: _item

- name: Git checkout scotch
  git:
    repo: "{{ scotch_source_url }}"
    dest: "{{ scotch_download_path }}"
    version: "v{{ scotch_version }}"

- name: Copy sources into build directory
  git:
    repo: "{{ scotch_download_path }}"
    dest: "{{ scotch_build_path }}"
    version: "v{{ scotch_version }}"
    force: true

#- name: Download scotch sources
#  get_url:
#    url: "{{ scotch_source_url }}"
#    dest: "{{ download_dir }}"
#  register: scotch_source_archive
#
#- name: Unarchive file
#  unarchive:
#    src: "{{ scotch_source_archive.dest }}"
#    dest: "{{ scotch_download_path }}"
#    remote_src: yes
#  register: scotch_source_dir
#
- name: Add Makefile.inc for scotch
  template:
    src: "{{ _item  }}"
    dest: "{{ scotch_build_path }}/src/Makefile.inc"
  loop_control:
    loop_var: _item
  with_items:
    - "Makefile.inc.j2"

- name: Replace prefix in makefile
  replace:
    path: "{{ scotch_build_path }}/src/Makefile"
    regexp: "^prefix\\s*\\?\\=.*$"
    replace: "prefix ?= {{ scotch_install_dir }}"
#    backup: yes

# Installing
- name: Install scotch
  command: " {{ _item }} "
  args:
    chdir: "{{ scotch_build_path }}/src"
  with_items:
    - "{{ scotch_make_program }} -j {{ scotch_make_jobs }}"
    - "{{ scotch_make_program }} install"
  loop_control:
    loop_var: _item
#  environment:
#    LD_LIBRARY_PATH: "{{ GCC_LD }}"
#
- name: Cleaning
  file:
    state: absent
    path: "{{ item }}/"
  with_items:
    - "{{ scotch_build_path }}"
