---
# main tasks file for ptscotch

- name: Setting ptscotch facts
  include_tasks: pre.yml

- name: Prerequisities check
  include_tasks: assert.yml

- name: "Install {{ role_name | upper }} version {{ ptscotch_version }}"
  include_tasks: install.yml
  when: ptscotch_build_needed is defined

- name: "Create a module for {{ role_name | upper }}"
  include_tasks: modulefile.yml
  when: ptscotch_module|bool

- name: include info.yml
  include_tasks: info.yml