---
# main tasks file for scotch

- name: Setting scotch facts
  include_tasks: pre.yml

- name: Prerequisities check
  include_tasks: assert.yml

- name: "Install {{ role_name | upper }} version {{ scotch_version }}"
  include_tasks: install.yml
  when: scotch_build_needed is defined

- name: "Create a module for {{ role_name | upper }}"
  include_tasks: modulefile.yml
  when: scotch_module|bool

- name: include info.yml
  include_tasks: info.yml