---
# modulefile for scotch

- name: Creates scotch directories if not exists
  file:
    path: "{{ scotch_module_dir }}"
    state: directory

- name: Add modulefile for scotch
  template:
    src: "{{ _item  }}"
    dest: "{{ scotch_module_dir }}/{{ _item  | regex_replace('module.j2', scotch_version ) }}"
  loop_control:
    loop_var: _item
  with_items:
    - "module.j2"
  vars:
    pkg_home: "{{ scotch_install_dir }}"
    pkg_name: "{{ role_name }}"
    pkg_ver: "{{ scotch_version }}"
    pkg_compiler: "gcc-{{ gcc_version }}"