---
# Settings some facts for scotch

- name: Define required directories
  set_fact:
    build_dir: "{{ build_dir | default( '/tmp/build' ) }}"
    download_dir: "{{ download_dir | default( '/tmp/download' ) }}"
    modules_home: "{{ modules_home | default( '/etc/modulefiles' ) }}"

- name: Decompose version
  set_fact:
    scotch_major_version: "{{ scotch_version.split('.')[0] }}"
    scotch_micro_version: "{{ scotch_version.split('.')[1] }}"
    scotch_minor_version: "{{ scotch_version.split('.')[2] }}"

- name: Define download, checksum urls
  set_fact:
    scotch_source_url: https://gitlab.inria.fr/scotch/scotch.git
#    scotch_source_url: "https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_{{ scotch_version }}.tar.gz"

- name: Set scotch paths
  set_fact:
    scotch_build_path: "{{ build_dir }}/{{ role_name }}/{{ scotch_version }}"
    scotch_download_path: "{{ download_dir }}/{{ role_name }}/{{ scotch_version }}"

- name: Define scotch install directory
  set_fact:
    scotch_install_dir: "{{ scotch_install_dir | default( ['/opt', role_name, [ [scotch_version, gcc_version] | join('-gcc'), openmpi_version ]\
     | join('-ompi') ] | join('/') ) }}"

- name: Define scotch src directory
  set_fact:
    scotch_src_dir: "{{ scotch_download_path }}/src"

- name: Define number of jobs for the build process
  set_fact:
    scotch_make_jobs: "{{ scotch_make_jobs | default(4) }}"

- name: Define module_home variable if not previously defined
  set_fact:
    modules_home: "{{ modules_home | default( '/etc/modulefiles' ) }}"
  when: scotch_module|bool

- name: Define scotch_module_dir variable
  set_fact:
    scotch_module_dir: "{{ modules_home }}/scotch/"
  when: scotch_module|bool